### ISSUE TITLE
request - add examples for PythonParse in jiter

### ISSUE THREAD

**Issue by sansyrox** [pydantic/jiter#107]
Hi,

I am the author of Robyn(https://github.com/sparckles/Robyn/) , and I have been following jiter for a while. I saw a tweet of Samuel recently saying that jiter has achieved performance equivalent to orjson.

I would love to use it in Robyn if that is the case. Would it be possible to have some documentation of the PythonParse struct?

Thanks in advance.

**Comment by samuelcolvin** [comment]
Thanks for the interest @sansyrox. There's a nice example in python package here:

https://github.com/pydantic/jiter/blob/366d16a24c113d01d96c6a6676cdfb7f00fcdcdc/crates/jiter-python/src/lib.rs#L29-L38
