### ISSUE TITLE
"Benchmarks" link in the README is a 404

### ISSUE THREAD

**Issue by AlexWaygood** [pydantic/jiter#122]
The README links to https://github.com/pydantic/jiter/tree/main/benches, but there's no `benches/` directory in the repo root on the `main` branch

**Comment by AlexWaygood** [comment]
Guessing it should be https://github.com/pydantic/jiter/tree/main/crates/jiter/benches?

**Comment by samuelcolvin** [comment]
yes good point, I'll fix.
