### ISSUE TITLE
Would you consider making bigint support optional?

### ISSUE THREAD

**Issue by fasterthanlime** [pydantic/jiter#124]
`num-bigint` is not small — I'd like to make bigint support optional in [merde_json](https://github.com/bearcove/merde_json) and I'd be happy to submit a PR to put bigint support behind a feature flag in jiter.

**Comment by davidhewitt** [comment]
I think it should be possible to make it a compile-time only effect, so personally I'd be happy to accept such a PR. Might want to let @samuelcolvin confirm before coding it up, depending how much work it is to prepare :)
