### ISSUE TITLE
Publish this package to PyPi?

### ISSUE THREAD

**Issue by RobertCraigie** [pydantic/jiter#92]
Hey! I really want to make use of the new partial JSON parsing support in one of the libraries I maintain but we've been maintaining compatibility with Pydantic v1 and it's still getting a lot of usage so we can't bump our minimum version requirement just yet :/

Would you be open to publishing this parser as a separate package to PyPi so we can add that as a dependency instead?

**Comment by samuelcolvin** [comment]
Yes we will, that's the plan.

**Comment by RobertCraigie** [comment]
Awesome! Any planned timeline you can share?

**Comment by samuelcolvin** [comment]
As soon as I have time.

Sorry, I can't be more specific than that.

**Comment by samuelcolvin** [comment]
https://pypi.org/project/jiter/ done

**Comment by RobertCraigie** [comment]
Thank you so much!
